version: '3'
services:
  strapi:
    build: .
    ports:
      - '1337:1337'
    environment:
      DATABASE_CLIENT: sqlite
      DATABASE_FILENAME: './data/data.sqlite'
    volumes:
      - ./data:/app/data
